version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html &&
      chmod -R 755 /var/www/html &&
      apache2-foreground"
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
volumes:
  db_data:
